services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql_server
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
