export class Lists {
    static CodeLanguage = [
        {value: 'Assembly Language', display: 'Assembly Language'},
        {value: 'Ada', display: 'Ada'},
        {value: 'Bash', display: 'Bash'},
        {value: 'C', display: 'C'},
        {value: 'C#', display: 'C#'},
        {value: 'COBOL', display: 'COBOL'},
        {value: 'D', display: 'D'},
        {value: 'Dart', display: 'Dart'},
        {value: 'Delphi', display: 'Delphi'},
        {value: 'Fortran', display: 'Fortran'},
        {value: 'Go', display: 'Go'},
        {value: 'Haskell', display: 'Haskell'},
        {value: 'Java', display: 'Java'},
        {value: 'JavaScript', display: 'JavaScript'},
        {value: 'Julia', display: 'Julia'},
        {value: 'Kotlin', display: 'Kotlin'},
        {value: 'Lisp', display: 'Lisp'},
        {value: 'Logo', display: 'Logo'},
        {value: 'Lua', display: 'Lua'},
        {value: 'MATLAB', display: 'MATLAB'},
        {value: 'Objective C', display: 'Objective C'},
        {value: 'Perl', display: 'Perl'},
        {value: 'PHP', display: 'PHP'},
        {value: 'Prolog', display: 'Prolog'},
        {value: 'Python', display: 'Python'},
        {value: 'R', display: 'R'},
        {value: 'Ruby', display: 'Ruby'},
        {value: 'Rust', display: 'Rust'},
        {value: 'SAS', display: 'SAS'},
        {value: 'Scala', display: 'Scala'},
        {value: 'Scratch', display: 'Scratch'},
        {value: 'SQL', display: 'SQL'},
        {value: 'Swift', display: 'Swift'},
        {value: 'Transact SQL', display: 'Transact SQL'},
        {value: 'Visual Basic', display: 'Visual Basic'}
    ];
    static Country = [
        {value: 'Albania', display: 'Albania'},
        {value: 'Andorra', display: 'Andorra'},
        {value: 'Austria', display: 'Austria'},
        {value: 'Belarus', display: 'Belarus'},
        {value: 'Belgium', display: 'Belgium'},
        {value: 'Bosnia and Herzegovina', display: 'Bosnia and Herzegovina'},
        {value: 'Bulgaria', display: 'Bulgaria'},
        {value: 'Croatia', display: 'Croatia'},
        {value: 'Czech Republic', display: 'Czech Republic'},
        {value: 'Denmark', display: 'Denmark'},
        {value: 'Estonia', display: 'Estonia'},
        {value: 'Finland', display: 'Finland'},
        {value: 'France', display: 'France'},
        {value: 'Germany', display: 'Germany'},
        {value: 'Greece', display: 'Greece'},
        {value: 'Hungary', display: 'Hungary'},
        {value: 'Iceland', display: 'Iceland'},
        {value: 'Italy', display: 'Italy'},
        {value: 'Latvia', display: 'Latvia'},
        {value: 'Liechtenstein', display: 'Liechtenstein'},
        {value: 'Lithuania', display: 'Lithuania'},
        {value: 'Luxembourg', display: 'Luxembourg'},
        {value: 'Malta', display: 'Malta'},
        {value: 'Moldova', display: 'Moldova'},
        {value: 'Monaco', display: 'Monaco'},
        {value: 'Montenegro', display: 'Montenegro'},
        {value: 'Netherlands', display: 'Netherlands'},
        {value: 'North Macedonia', display: 'North Macedonia'},
        {value: 'Norway', display: 'Norway'},
        {value: 'Poland', display: 'Poland'},
        {value: 'Portugal', display: 'Portugal'},
        {value: 'Romania', display: 'Romania'},
        {value: 'Russia', display: 'Russia'},
        {value: 'San Marino', display: 'San Marino'},
        {value: 'Serbia', display: 'Serbia'},
        {value: 'Slovakia', display: 'Slovakia'},
        {value: 'Slovenia', display: 'Slovenia'},
        {value: 'Spain', display: 'Spain'},
        {value: 'Sweden', display: 'Sweden'},
        {value: 'Switzerland', display: 'Switzerland'},
        {value: 'Ukraine', display: 'Ukraine'},
        {value: 'United Kingdom', display: 'United Kingdom'}
    ];
    static RandomPhotoURL = [
        'https://images.unsplash.com/photo-1690729356341-bbd33d01d2db?auto=format&fit=crop&q=80&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=2081',
        'https://images.unsplash.com/photo-1673365612839-70c479268d70?auto=format&fit=crop&q=80&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=2080'
    ]
}